apiVersion: v1
kind: PersistentVolume
metadata:
  name: express-practice-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "express-practice"
  hostPath:
    path: "/Users/tony/Desktop/app"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: express-practice-pvc
spec:
  storageClassName: "express-practice"
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-practice-deployment
spec:
  selector:
    matchLabels:
      app: express-practice-app
  template:
    metadata:
      labels:
        app: express-practice-app
    spec:
      containers:
        - name: express-practice-app
          image: tony3527657/express-practice
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/logs
              name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: express-practice-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: express-practice-service
spec:
  selector:
    app: express-practice-app
  ports:
    - port: 3000
      targetPort: 3000
