apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-practice-deployment
spec:
  selector:
    matchLabels:
      app: express-practice-app
  template:
    metadata:
      labels:
        app: express-practice-app
    spec:
      containers:
        - name: express-practice-app
          image: tony3527657/express-practice
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: express-practice-service
spec:
  selector:
    app: express-practice-app
  ports:
    - port: 3000
      targetPort: 3000
